name: 'FDM'
jog_type: "c2i"
output_dir: "./logs/${config.jog_type}/${config.name}"

#****** Data Settings ******
image_size: 256

class_list_path: "path to class list"
data_path: "path to data source"
proj_path: "path to label projection"

data_quantity: 100
train_data_ratio: 0.6
val_data_ratio: 0.2
test_data_ratio: 0.2

FDM:
  img_size_list: [16, 4, 1]
  patch_size_list: [4, 2, 1]
  embed_dim_list: [768,384,384]
  num_head_list: [12,6,6]
  depth_list: [12,12,12]
  timestep_list: [400,300,300]
  max_patches_per_step: 2048
  class_num: 1000

scheduler:
  step_size: 50
  gamma: 0.8


trainer:
  devices: [1]
  accelerator: "auto"
  max_epochs: 1000
  precision: 16-mixed
  check_val_every_n_epoch: 10
  # strategy: "ddp_find_unused_parameters_true"
